### ISSUE TITLE
Nice application!

### ISSUE THREAD

**Issue by kelegorm** [orlv/freeshuttercounter#1]
Is it ObjectiveC? Do you wanna try Swift 2?

**Comment by orlv** [comment]
Привет, Дима! :) Да какая уж тут разница, программа то маленькая. Следующую сделаю на Swift.

**Comment by kelegorm** [comment]
у меня есть программка на обжекте, маленькая. Вот думаю ее как-то переписать на Swift. но ничерта не могу понять в этом обжективе и файлах проекта.

**Comment by orlv** [comment]
Да что тут понимать, это же обычный си с маленьким дополнением. Скинь ссылку, дай посмотреть, что там? :)

PS: нет ли у тебя какого-нибудь мессенджера, через который можно было бы общаться?

**Comment by kelegorm** [comment]
Это чужой проект, таймер рабочего времени. Хотел его адаптировать к своему будущему проекту по управлению задачами. Вот он: https://github.com/kelegorm/awareness

Я вот думал его сначала просто переписать на новый свифт, как-нить займусь, для изучения и дальнейшей пользы.

Контакты отправил тебе в почту
