### ISSUE TITLE
Unable to Uninstall on BigSur

### ISSUE THREAD

**Issue by jbfsg** [orlv/freeshuttercounter#10]
I attempted to use this program on a T7 rebel unfortunately did not work when I deleted it it still appears on the Launchpad is there some sort of uninstall procedure or do I got to wipe my computer?

**Comment by orlv** [comment]
Open Finder, go to Applications folder. Find freeshuttercounter and move it to the trash bin.

**Comment by jbfsg** [comment]
Thank you for the reply. Originally I did do as you instructed before posting on here. Shortly after I clicked on the application logo as if to "open" to make the OS realize it was "x/?" application. After that it let me drag it to the Trash bin (through the launchpad.)

Perhaps I can erase my thread or I can leave it for future reference to others.
________________________________
